/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        "on-surface": "#151c25",
        "on-secondary-container": "#007432",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1fe",
        "secondary-container": "#6bff8f",
        "on-primary-fixed-variant": "#404758",
        "primary-fixed": "#dce2f7",
        "inverse-surface": "#2a313b",
        "on-primary-container": "#7d8497",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ef4444",
        "surface-container-high": "#e2e8f5",
        "primary-fixed-dim": "#c0c6db",
        "outline": "#76777d",
        "secondary-fixed": "#6bff8f",
        "tertiary": "#000000",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "surface-container-low": "#eef4ff",
        "tertiary-fixed": "#ffdad7",
        "on-secondary-fixed": "#002109",
        "on-surface-variant": "#45464c",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#930013",
        "primary-container": "#141b2b",
        "surface-container": "#e7eefb",
        "on-tertiary": "#ffffff",
        "surface-tint": "#575e70",
        "outline-variant": "#c6c6cd",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#141b2b",
        "on-primary": "#ffffff",
        "tertiary-container": "#410004",
        "background": "#f8f9ff",
        "secondary": "#006e2f",
        "primary": "#000000",
        "on-tertiary-fixed": "#410004",
        "secondary-fixed-dim": "#4ae176",
        "on-background": "#151c25",
        "inverse-primary": "#c0c6db",
        "on-error-container": "#93000a",
        "surface-variant": "#dce3f0",
        "surface-dim": "#d4dae7",
        "on-secondary-fixed-variant": "#005321",
        "surface-container-highest": "#dce3f0"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sm": "8px",
        "margin-mobile": "16px",
        "xs": "4px",
        "md": "16px",
        "margin-desktop": "32px",
        "unit": "4px",
        "gutter": "16px",
        "xl": "32px",
        "lg": "24px"
      },
      fontFamily: {
        "sans": ["Inter", "ui-sans-serif", "system-ui"],
        "mono": ["JetBrains Mono", "ui-monospace"],
      },
      fontSize: {
        "data-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "data-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
